### ISSUE TITLE
install mosestokenizer

### ISSUE THREAD

**Issue by ji-in** [ji-in/NLG#2]
C:\Users\jiinkim\Desktop\corpus_data>pip install mosestokenizer
Collecting mosestokenizer
  Downloading mosestokenizer-1.1.0.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jiinkim\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jiinkim\\AppData\\Local\\Temp\\pip-install-4y3x9h4o\\mosestokenizer\\setup.py'"'"'; __file__='"'"'C:\\Users\\jiinkim\\AppData\\Local\\Temp\\pip-install-4y3x9h4o\\mosestokenizer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jiinkim\AppData\Local\Temp\pip-pip-egg-info-ja0rbud_'
         cwd: C:\Users\jiinkim\AppData\Local\Temp\pip-install-4y3x9h4o\mosestokenizer\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jiinkim\AppData\Local\Temp\pip-install-4y3x9h4o\mosestokenizer\setup.py", line 31, in <module>
        long_description=read('README.rst'),
      File "C:\Users\jiinkim\AppData\Local\Temp\pip-install-4y3x9h4o\mosestokenizer\setup.py", line 12, in read
        return f.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2399: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.  

영어 문장들을 tokenize하기 위해 mosestokenizer를 설치하려고 하는데, 에러가 발생한다.

**Comment by ji-in** [comment]
msesetokenizer package는 도저히 안깔려서 [여기](https://github.com/alvations/sacremoses)를 사용했다.
